// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v5.28.2
// source: fishjam/media_events/peer/peer.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Candidate, Metadata, MidToTrackId, Variant, variantFromJSON, variantToJSON } from "../shared";

export const protobufPackage = "fishjam.media_events.peer";

/** Defines any type of message sent from Peer to Membrane RTC Engine */
export interface MediaEvent {
  connect?: MediaEvent_Connect | undefined;
  disconnect?: MediaEvent_Disconnect | undefined;
  updateEndpointMetadata?: MediaEvent_UpdateEndpointMetadata | undefined;
  updateTrackMetadata?: MediaEvent_UpdateTrackMetadata | undefined;
  renegotiateTracks?: MediaEvent_RenegotiateTracks | undefined;
  candidate?: Candidate | undefined;
  sdpOffer?: MediaEvent_SdpOffer | undefined;
  trackBitrate?: MediaEvent_TrackBitrate | undefined;
}

/** SCHEMAS */
export interface MediaEvent_VariantBitrate {
  variant: Variant;
  bitrate: number;
}

export interface MediaEvent_TrackIdToMetadata {
  trackId: string;
  metadata: Metadata | undefined;
}

export interface MediaEvent_TrackIdToBitrates {
  trackBitrate?: MediaEvent_TrackBitrate | undefined;
}

/** Sent when a peer wants to join WebRTC Endpoint. */
export interface MediaEvent_Connect {
  metadata: Metadata | undefined;
}

/** Sent when a peer disconnects from WebRTC Endpoint. */
export interface MediaEvent_Disconnect {
}

/** Sent when a peer wants to update its metadata */
export interface MediaEvent_UpdateEndpointMetadata {
  metadata: Metadata | undefined;
}

/** Sent when a peer wants to update its track's metadata */
export interface MediaEvent_UpdateTrackMetadata {
  trackId: string;
  metadata: Metadata | undefined;
}

/** Sent when peer wants to renegatiate connection due to adding a track or removing a track */
export interface MediaEvent_RenegotiateTracks {
}

/**
 * Sent as a response to `offerData` media event during renegotiation
 * Maps contain only information about current peer's `sendonly` tracks.
 * The "mid" is an identifier used to associate an RTP packet with an MLine from the SDP offer/answer.
 */
export interface MediaEvent_SdpOffer {
  sdpOffer: string;
  trackIdToMetadata: MediaEvent_TrackIdToMetadata[];
  trackIdToBitrates: MediaEvent_TrackIdToBitrates[];
  midToTrackId: MidToTrackId[];
}

/** Sent when Peer wants to update its track's bitrate */
export interface MediaEvent_TrackBitrate {
  trackId: string;
  bitrate: number;
}

function createBaseMediaEvent(): MediaEvent {
  return {
    connect: undefined,
    disconnect: undefined,
    updateEndpointMetadata: undefined,
    updateTrackMetadata: undefined,
    renegotiateTracks: undefined,
    candidate: undefined,
    sdpOffer: undefined,
    trackBitrate: undefined,
  };
}

export const MediaEvent: MessageFns<MediaEvent> = {
  encode(message: MediaEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.connect !== undefined) {
      MediaEvent_Connect.encode(message.connect, writer.uint32(10).fork()).join();
    }
    if (message.disconnect !== undefined) {
      MediaEvent_Disconnect.encode(message.disconnect, writer.uint32(18).fork()).join();
    }
    if (message.updateEndpointMetadata !== undefined) {
      MediaEvent_UpdateEndpointMetadata.encode(message.updateEndpointMetadata, writer.uint32(26).fork()).join();
    }
    if (message.updateTrackMetadata !== undefined) {
      MediaEvent_UpdateTrackMetadata.encode(message.updateTrackMetadata, writer.uint32(34).fork()).join();
    }
    if (message.renegotiateTracks !== undefined) {
      MediaEvent_RenegotiateTracks.encode(message.renegotiateTracks, writer.uint32(42).fork()).join();
    }
    if (message.candidate !== undefined) {
      Candidate.encode(message.candidate, writer.uint32(50).fork()).join();
    }
    if (message.sdpOffer !== undefined) {
      MediaEvent_SdpOffer.encode(message.sdpOffer, writer.uint32(58).fork()).join();
    }
    if (message.trackBitrate !== undefined) {
      MediaEvent_TrackBitrate.encode(message.trackBitrate, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.connect = MediaEvent_Connect.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.disconnect = MediaEvent_Disconnect.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updateEndpointMetadata = MediaEvent_UpdateEndpointMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.updateTrackMetadata = MediaEvent_UpdateTrackMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.renegotiateTracks = MediaEvent_RenegotiateTracks.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.candidate = Candidate.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sdpOffer = MediaEvent_SdpOffer.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.trackBitrate = MediaEvent_TrackBitrate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaEvent {
    return {
      connect: isSet(object.connect) ? MediaEvent_Connect.fromJSON(object.connect) : undefined,
      disconnect: isSet(object.disconnect) ? MediaEvent_Disconnect.fromJSON(object.disconnect) : undefined,
      updateEndpointMetadata: isSet(object.updateEndpointMetadata)
        ? MediaEvent_UpdateEndpointMetadata.fromJSON(object.updateEndpointMetadata)
        : undefined,
      updateTrackMetadata: isSet(object.updateTrackMetadata)
        ? MediaEvent_UpdateTrackMetadata.fromJSON(object.updateTrackMetadata)
        : undefined,
      renegotiateTracks: isSet(object.renegotiateTracks)
        ? MediaEvent_RenegotiateTracks.fromJSON(object.renegotiateTracks)
        : undefined,
      candidate: isSet(object.candidate) ? Candidate.fromJSON(object.candidate) : undefined,
      sdpOffer: isSet(object.sdpOffer) ? MediaEvent_SdpOffer.fromJSON(object.sdpOffer) : undefined,
      trackBitrate: isSet(object.trackBitrate) ? MediaEvent_TrackBitrate.fromJSON(object.trackBitrate) : undefined,
    };
  },

  toJSON(message: MediaEvent): unknown {
    const obj: any = {};
    if (message.connect !== undefined) {
      obj.connect = MediaEvent_Connect.toJSON(message.connect);
    }
    if (message.disconnect !== undefined) {
      obj.disconnect = MediaEvent_Disconnect.toJSON(message.disconnect);
    }
    if (message.updateEndpointMetadata !== undefined) {
      obj.updateEndpointMetadata = MediaEvent_UpdateEndpointMetadata.toJSON(message.updateEndpointMetadata);
    }
    if (message.updateTrackMetadata !== undefined) {
      obj.updateTrackMetadata = MediaEvent_UpdateTrackMetadata.toJSON(message.updateTrackMetadata);
    }
    if (message.renegotiateTracks !== undefined) {
      obj.renegotiateTracks = MediaEvent_RenegotiateTracks.toJSON(message.renegotiateTracks);
    }
    if (message.candidate !== undefined) {
      obj.candidate = Candidate.toJSON(message.candidate);
    }
    if (message.sdpOffer !== undefined) {
      obj.sdpOffer = MediaEvent_SdpOffer.toJSON(message.sdpOffer);
    }
    if (message.trackBitrate !== undefined) {
      obj.trackBitrate = MediaEvent_TrackBitrate.toJSON(message.trackBitrate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent>, I>>(base?: I): MediaEvent {
    return MediaEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent>, I>>(object: I): MediaEvent {
    const message = createBaseMediaEvent();
    message.connect = (object.connect !== undefined && object.connect !== null)
      ? MediaEvent_Connect.fromPartial(object.connect)
      : undefined;
    message.disconnect = (object.disconnect !== undefined && object.disconnect !== null)
      ? MediaEvent_Disconnect.fromPartial(object.disconnect)
      : undefined;
    message.updateEndpointMetadata =
      (object.updateEndpointMetadata !== undefined && object.updateEndpointMetadata !== null)
        ? MediaEvent_UpdateEndpointMetadata.fromPartial(object.updateEndpointMetadata)
        : undefined;
    message.updateTrackMetadata = (object.updateTrackMetadata !== undefined && object.updateTrackMetadata !== null)
      ? MediaEvent_UpdateTrackMetadata.fromPartial(object.updateTrackMetadata)
      : undefined;
    message.renegotiateTracks = (object.renegotiateTracks !== undefined && object.renegotiateTracks !== null)
      ? MediaEvent_RenegotiateTracks.fromPartial(object.renegotiateTracks)
      : undefined;
    message.candidate = (object.candidate !== undefined && object.candidate !== null)
      ? Candidate.fromPartial(object.candidate)
      : undefined;
    message.sdpOffer = (object.sdpOffer !== undefined && object.sdpOffer !== null)
      ? MediaEvent_SdpOffer.fromPartial(object.sdpOffer)
      : undefined;
    message.trackBitrate = (object.trackBitrate !== undefined && object.trackBitrate !== null)
      ? MediaEvent_TrackBitrate.fromPartial(object.trackBitrate)
      : undefined;
    return message;
  },
};

function createBaseMediaEvent_VariantBitrate(): MediaEvent_VariantBitrate {
  return { variant: 0, bitrate: 0 };
}

export const MediaEvent_VariantBitrate: MessageFns<MediaEvent_VariantBitrate> = {
  encode(message: MediaEvent_VariantBitrate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.variant !== 0) {
      writer.uint32(8).int32(message.variant);
    }
    if (message.bitrate !== 0) {
      writer.uint32(16).int32(message.bitrate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_VariantBitrate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_VariantBitrate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.variant = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bitrate = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaEvent_VariantBitrate {
    return {
      variant: isSet(object.variant) ? variantFromJSON(object.variant) : 0,
      bitrate: isSet(object.bitrate) ? globalThis.Number(object.bitrate) : 0,
    };
  },

  toJSON(message: MediaEvent_VariantBitrate): unknown {
    const obj: any = {};
    if (message.variant !== 0) {
      obj.variant = variantToJSON(message.variant);
    }
    if (message.bitrate !== 0) {
      obj.bitrate = Math.round(message.bitrate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_VariantBitrate>, I>>(base?: I): MediaEvent_VariantBitrate {
    return MediaEvent_VariantBitrate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_VariantBitrate>, I>>(object: I): MediaEvent_VariantBitrate {
    const message = createBaseMediaEvent_VariantBitrate();
    message.variant = object.variant ?? 0;
    message.bitrate = object.bitrate ?? 0;
    return message;
  },
};

function createBaseMediaEvent_TrackIdToMetadata(): MediaEvent_TrackIdToMetadata {
  return { trackId: "", metadata: undefined };
}

export const MediaEvent_TrackIdToMetadata: MessageFns<MediaEvent_TrackIdToMetadata> = {
  encode(message: MediaEvent_TrackIdToMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackId !== "") {
      writer.uint32(10).string(message.trackId);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_TrackIdToMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_TrackIdToMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trackId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaEvent_TrackIdToMetadata {
    return {
      trackId: isSet(object.trackId) ? globalThis.String(object.trackId) : "",
      metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined,
    };
  },

  toJSON(message: MediaEvent_TrackIdToMetadata): unknown {
    const obj: any = {};
    if (message.trackId !== "") {
      obj.trackId = message.trackId;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_TrackIdToMetadata>, I>>(base?: I): MediaEvent_TrackIdToMetadata {
    return MediaEvent_TrackIdToMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_TrackIdToMetadata>, I>>(object: I): MediaEvent_TrackIdToMetadata {
    const message = createBaseMediaEvent_TrackIdToMetadata();
    message.trackId = object.trackId ?? "";
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseMediaEvent_TrackIdToBitrates(): MediaEvent_TrackIdToBitrates {
  return { trackBitrate: undefined };
}

export const MediaEvent_TrackIdToBitrates: MessageFns<MediaEvent_TrackIdToBitrates> = {
  encode(message: MediaEvent_TrackIdToBitrates, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackBitrate !== undefined) {
      MediaEvent_TrackBitrate.encode(message.trackBitrate, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_TrackIdToBitrates {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_TrackIdToBitrates();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trackBitrate = MediaEvent_TrackBitrate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaEvent_TrackIdToBitrates {
    return {
      trackBitrate: isSet(object.trackBitrate) ? MediaEvent_TrackBitrate.fromJSON(object.trackBitrate) : undefined,
    };
  },

  toJSON(message: MediaEvent_TrackIdToBitrates): unknown {
    const obj: any = {};
    if (message.trackBitrate !== undefined) {
      obj.trackBitrate = MediaEvent_TrackBitrate.toJSON(message.trackBitrate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_TrackIdToBitrates>, I>>(base?: I): MediaEvent_TrackIdToBitrates {
    return MediaEvent_TrackIdToBitrates.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_TrackIdToBitrates>, I>>(object: I): MediaEvent_TrackIdToBitrates {
    const message = createBaseMediaEvent_TrackIdToBitrates();
    message.trackBitrate = (object.trackBitrate !== undefined && object.trackBitrate !== null)
      ? MediaEvent_TrackBitrate.fromPartial(object.trackBitrate)
      : undefined;
    return message;
  },
};

function createBaseMediaEvent_Connect(): MediaEvent_Connect {
  return { metadata: undefined };
}

export const MediaEvent_Connect: MessageFns<MediaEvent_Connect> = {
  encode(message: MediaEvent_Connect, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_Connect {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_Connect();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaEvent_Connect {
    return { metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined };
  },

  toJSON(message: MediaEvent_Connect): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_Connect>, I>>(base?: I): MediaEvent_Connect {
    return MediaEvent_Connect.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_Connect>, I>>(object: I): MediaEvent_Connect {
    const message = createBaseMediaEvent_Connect();
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseMediaEvent_Disconnect(): MediaEvent_Disconnect {
  return {};
}

export const MediaEvent_Disconnect: MessageFns<MediaEvent_Disconnect> = {
  encode(_: MediaEvent_Disconnect, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_Disconnect {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_Disconnect();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MediaEvent_Disconnect {
    return {};
  },

  toJSON(_: MediaEvent_Disconnect): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_Disconnect>, I>>(base?: I): MediaEvent_Disconnect {
    return MediaEvent_Disconnect.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_Disconnect>, I>>(_: I): MediaEvent_Disconnect {
    const message = createBaseMediaEvent_Disconnect();
    return message;
  },
};

function createBaseMediaEvent_UpdateEndpointMetadata(): MediaEvent_UpdateEndpointMetadata {
  return { metadata: undefined };
}

export const MediaEvent_UpdateEndpointMetadata: MessageFns<MediaEvent_UpdateEndpointMetadata> = {
  encode(message: MediaEvent_UpdateEndpointMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_UpdateEndpointMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_UpdateEndpointMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaEvent_UpdateEndpointMetadata {
    return { metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined };
  },

  toJSON(message: MediaEvent_UpdateEndpointMetadata): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_UpdateEndpointMetadata>, I>>(
    base?: I,
  ): MediaEvent_UpdateEndpointMetadata {
    return MediaEvent_UpdateEndpointMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_UpdateEndpointMetadata>, I>>(
    object: I,
  ): MediaEvent_UpdateEndpointMetadata {
    const message = createBaseMediaEvent_UpdateEndpointMetadata();
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseMediaEvent_UpdateTrackMetadata(): MediaEvent_UpdateTrackMetadata {
  return { trackId: "", metadata: undefined };
}

export const MediaEvent_UpdateTrackMetadata: MessageFns<MediaEvent_UpdateTrackMetadata> = {
  encode(message: MediaEvent_UpdateTrackMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackId !== "") {
      writer.uint32(10).string(message.trackId);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_UpdateTrackMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_UpdateTrackMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trackId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaEvent_UpdateTrackMetadata {
    return {
      trackId: isSet(object.trackId) ? globalThis.String(object.trackId) : "",
      metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined,
    };
  },

  toJSON(message: MediaEvent_UpdateTrackMetadata): unknown {
    const obj: any = {};
    if (message.trackId !== "") {
      obj.trackId = message.trackId;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_UpdateTrackMetadata>, I>>(base?: I): MediaEvent_UpdateTrackMetadata {
    return MediaEvent_UpdateTrackMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_UpdateTrackMetadata>, I>>(
    object: I,
  ): MediaEvent_UpdateTrackMetadata {
    const message = createBaseMediaEvent_UpdateTrackMetadata();
    message.trackId = object.trackId ?? "";
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseMediaEvent_RenegotiateTracks(): MediaEvent_RenegotiateTracks {
  return {};
}

export const MediaEvent_RenegotiateTracks: MessageFns<MediaEvent_RenegotiateTracks> = {
  encode(_: MediaEvent_RenegotiateTracks, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_RenegotiateTracks {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_RenegotiateTracks();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MediaEvent_RenegotiateTracks {
    return {};
  },

  toJSON(_: MediaEvent_RenegotiateTracks): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_RenegotiateTracks>, I>>(base?: I): MediaEvent_RenegotiateTracks {
    return MediaEvent_RenegotiateTracks.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_RenegotiateTracks>, I>>(_: I): MediaEvent_RenegotiateTracks {
    const message = createBaseMediaEvent_RenegotiateTracks();
    return message;
  },
};

function createBaseMediaEvent_SdpOffer(): MediaEvent_SdpOffer {
  return { sdpOffer: "", trackIdToMetadata: [], trackIdToBitrates: [], midToTrackId: [] };
}

export const MediaEvent_SdpOffer: MessageFns<MediaEvent_SdpOffer> = {
  encode(message: MediaEvent_SdpOffer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sdpOffer !== "") {
      writer.uint32(10).string(message.sdpOffer);
    }
    for (const v of message.trackIdToMetadata) {
      MediaEvent_TrackIdToMetadata.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.trackIdToBitrates) {
      MediaEvent_TrackIdToBitrates.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.midToTrackId) {
      MidToTrackId.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_SdpOffer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_SdpOffer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sdpOffer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.trackIdToMetadata.push(MediaEvent_TrackIdToMetadata.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.trackIdToBitrates.push(MediaEvent_TrackIdToBitrates.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.midToTrackId.push(MidToTrackId.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaEvent_SdpOffer {
    return {
      sdpOffer: isSet(object.sdpOffer) ? globalThis.String(object.sdpOffer) : "",
      trackIdToMetadata: globalThis.Array.isArray(object?.trackIdToMetadata)
        ? object.trackIdToMetadata.map((e: any) => MediaEvent_TrackIdToMetadata.fromJSON(e))
        : [],
      trackIdToBitrates: globalThis.Array.isArray(object?.trackIdToBitrates)
        ? object.trackIdToBitrates.map((e: any) => MediaEvent_TrackIdToBitrates.fromJSON(e))
        : [],
      midToTrackId: globalThis.Array.isArray(object?.midToTrackId)
        ? object.midToTrackId.map((e: any) => MidToTrackId.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MediaEvent_SdpOffer): unknown {
    const obj: any = {};
    if (message.sdpOffer !== "") {
      obj.sdpOffer = message.sdpOffer;
    }
    if (message.trackIdToMetadata?.length) {
      obj.trackIdToMetadata = message.trackIdToMetadata.map((e) => MediaEvent_TrackIdToMetadata.toJSON(e));
    }
    if (message.trackIdToBitrates?.length) {
      obj.trackIdToBitrates = message.trackIdToBitrates.map((e) => MediaEvent_TrackIdToBitrates.toJSON(e));
    }
    if (message.midToTrackId?.length) {
      obj.midToTrackId = message.midToTrackId.map((e) => MidToTrackId.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_SdpOffer>, I>>(base?: I): MediaEvent_SdpOffer {
    return MediaEvent_SdpOffer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_SdpOffer>, I>>(object: I): MediaEvent_SdpOffer {
    const message = createBaseMediaEvent_SdpOffer();
    message.sdpOffer = object.sdpOffer ?? "";
    message.trackIdToMetadata = object.trackIdToMetadata?.map((e) => MediaEvent_TrackIdToMetadata.fromPartial(e)) || [];
    message.trackIdToBitrates = object.trackIdToBitrates?.map((e) => MediaEvent_TrackIdToBitrates.fromPartial(e)) || [];
    message.midToTrackId = object.midToTrackId?.map((e) => MidToTrackId.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMediaEvent_TrackBitrate(): MediaEvent_TrackBitrate {
  return { trackId: "", bitrate: 0 };
}

export const MediaEvent_TrackBitrate: MessageFns<MediaEvent_TrackBitrate> = {
  encode(message: MediaEvent_TrackBitrate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trackId !== "") {
      writer.uint32(10).string(message.trackId);
    }
    if (message.bitrate !== 0) {
      writer.uint32(16).int32(message.bitrate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MediaEvent_TrackBitrate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMediaEvent_TrackBitrate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trackId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bitrate = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MediaEvent_TrackBitrate {
    return {
      trackId: isSet(object.trackId) ? globalThis.String(object.trackId) : "",
      bitrate: isSet(object.bitrate) ? globalThis.Number(object.bitrate) : 0,
    };
  },

  toJSON(message: MediaEvent_TrackBitrate): unknown {
    const obj: any = {};
    if (message.trackId !== "") {
      obj.trackId = message.trackId;
    }
    if (message.bitrate !== 0) {
      obj.bitrate = Math.round(message.bitrate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MediaEvent_TrackBitrate>, I>>(base?: I): MediaEvent_TrackBitrate {
    return MediaEvent_TrackBitrate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MediaEvent_TrackBitrate>, I>>(object: I): MediaEvent_TrackBitrate {
    const message = createBaseMediaEvent_TrackBitrate();
    message.trackId = object.trackId ?? "";
    message.bitrate = object.bitrate ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
